const questionAnswerMap =
{
    "What is the role of primary care physicians in healthcare": "Primary care physicians serve as the first point of contact for patients, providing preventive care, managing chronic conditions, and coordinating specialized care when needed.",
    "How does vaccination work to prevent infectious diseases": "Vaccination works by introducing a weakened or killed form of a pathogen into the body, triggering the immune system to produce antibodies. These antibodies provide immunity against future infections by the same pathogen.",
    "What are the common risk factors for heart disease": "Common risk factors for heart disease include high blood pressure, high cholesterol levels, smoking, obesity, diabetes, and a sedentary lifestyle.",
    "What is the difference between a virus and a bacterium": "Viruses are infectious agents that require a host cell to replicate and cause disease, while bacteria are single-celled organisms that can live independently and reproduce on their own.",
    "How does exercise benefit overall health": "Regular exercise contributes to cardiovascular health, weight management, improved mood, increased energy levels, and reduced risk of chronic diseases such as diabetes and heart disease.",
    "What are the symptoms of the common cold": "Symptoms of the common cold include a runny or stuffy nose, sore throat, cough, sneezing, mild body aches, and low-grade fever.",
    "What is the purpose of antibiotics, and when are they appropriate for use": "Antibiotics are used to treat bacterial infections by killing or inhibiting the growth of bacteria. They are appropriate for bacterial infections but not effective against viral infections like the common cold or flu.",
    "How can individuals prevent the spread of infectious diseases": "Individuals can prevent the spread of infectious diseases by practicing good hygiene, including frequent handwashing, covering coughs and sneezes, staying home when sick, and getting vaccinated.",
    "What is the recommended frequency for routine health screenings": "The recommended frequency for routine health screenings varies depending on factors such as age, gender, and personal health history. Common screenings include blood pressure checks, cholesterol tests, mammograms, and colonoscopies.",
    "What are the benefits of maintaining a balanced diet": "A balanced diet provides essential nutrients for overall health and well-being, supports healthy growth and development, helps maintain a healthy weight, reduces the risk of chronic diseases, and promotes optimal bodily function.",
    "How does stress impact health": "Chronic stress can negatively affect physical and mental health, contributing to conditions such as high blood pressure, heart disease, obesity, depression, and anxiety.",
    "What is the importance of mental health awareness": "Mental health awareness is important for reducing stigma, promoting early intervention and treatment, fostering supportive communities, and improving overall quality of life for individuals affected by mental health conditions.",
    "What are some strategies for managing stress effectively": "Strategies for managing stress include practicing relaxation techniques such as deep breathing and meditation, engaging in regular physical activity, maintaining a healthy lifestyle, seeking social support, and setting realistic goals.",
    "How does smoking affect health": "Smoking is a major risk factor for various health problems, including lung cancer, heart disease, stroke, respiratory infections, and chronic obstructive pulmonary disease (COPD).",
    "What are the signs and symptoms of depression": "Signs and symptoms of depression may include persistent feelings of sadness or hopelessness, loss of interest in activities once enjoyed, changes in appetite or sleep patterns, fatigue, irritability, and difficulty concentrating.",
    "What are the benefits of regular sleep patterns": "Regular sleep patterns promote overall health and well-being by supporting cognitive function, mood regulation, immune function, and physical recovery. Adequate sleep is essential for optimal performance and productivity.",
    "How does alcohol consumption impact health": "Excessive alcohol consumption can lead to various health problems, including liver disease, heart disease, cancer, mental health disorders, impaired judgment, and addiction.",
    "What are the different types of cancer treatments available": "Cancer treatments include surgery, chemotherapy, radiation therapy, immunotherapy, targeted therapy, hormone therapy, and stem cell transplantation.",
    "What are the risk factors for developing skin cancer": "Risk factors for skin cancer include excessive sun exposure, history of sunburns, indoor tanning, fair skin, family history of skin cancer, and certain genetic factors.",
    "How does nutrition affect bone health": "Adequate intake of calcium, vitamin D, protein, and other nutrients is essential for maintaining strong and healthy bones throughout life and reducing the risk of osteoporosis and fractures.",
    "What are the symptoms of asthma": "Symptoms of asthma may include wheezing, coughing, shortness of breath, chest tightness, and difficulty breathing, especially during physical activity or exposure to triggers such as allergens or irritants.",
    "How does diabetes affect the eyes": "Diabetes can lead to diabetic retinopathy, a serious eye condition that damages the blood vessels in the retina and can cause vision loss or blindness if left untreated.",
    "What are the benefits of breastfeeding for both mother and baby": "Breastfeeding provides essential nutrients and antibodies for the baby, promotes bonding between mother and baby, reduces the risk of infections and chronic diseases for both mother and baby, and supports optimal growth and development.",
    "How does physical therapy help in rehabilitation": "Physical therapy helps restore movement and function, reduces pain, improves strength and flexibility, promotes healing and recovery, and prevents further injury through personalized exercise programs and therapeutic techniques.",
    "What are the symptoms of depression in older adults": "Symptoms of depression in older adults may include persistent sadness, fatigue, loss of interest in activities, changes in appetite or weight, sleep disturbances, feelings of worthlessness or guilt, and thoughts of death or suicide.",
    "How does the body regulate blood sugar levels": "The body regulates blood sugar levels through the actions of insulin, a hormone produced by the pancreas that helps cells absorb glucose from the bloodstream and store it for energy or use it as fuel.",
    "What are the long-term effects of untreated high blood pressure": "Untreated high blood pressure can lead to serious health complications, including heart disease, stroke, kidney disease, vision loss, peripheral artery disease, and cognitive decline.",
    "How does regular dental care contribute to overall health": "Regular dental care helps prevent oral health problems such as cavities, gum disease, and tooth loss, reduces the risk of systemic health conditions linked to poor oral health, and promotes overall well-being and quality of life.",
    "What are the benefits of regular eye exams": "Regular eye exams help detect vision problems, eye diseases, and other health conditions early when they are most treatable, preserve eye health and function, and maintain optimal vision throughout life.",
    "How does the body respond to stress": "The body responds to stress by releasing stress hormones such as cortisol and adrenaline, activating the 'fight or flight' response, increasing heart rate and blood pressure, and preparing the body to respond to perceived threats or challenges.",
    "What is the importance of maintaining a healthy gut microbiome": "A healthy gut microbiome is essential for digestion, nutrient absorption, immune function, hormone regulation, brain health, and protection against infections and diseases.",
    "What are the benefits of regular cardiovascular exercise": "Regular cardiovascular exercise strengthens the heart and lungs, improves circulation, lowers blood pressure, reduces the risk of heart disease and stroke, promotes weight loss and weight management, and enhances overall fitness and endurance.",
    "How does the body regulate temperature": "The body regulates temperature through processes such as sweating, shivering, vasodilation (expansion of blood vessels), and vasoconstriction (narrowing of blood vessels) to maintain a stable internal body temperature within a narrow range.",
    "What are the symptoms of food poisoning": "Symptoms of food poisoning may include nausea, vomiting, diarrhea, abdominal pain, fever, headache, muscle aches, and dehydration, depending on the type of bacteria, virus, or toxin ingested.",
    "What is the importance of proper hand hygiene in preventing infections": "Proper hand hygiene, including handwashing with soap and water or using hand sanitizer, is crucial for removing germs and reducing the spread of infections, including respiratory infections, gastrointestinal illnesses, and healthcare-associated infections.",
    "How does chronic stress contribute to health problems": "Chronic stress can contribute to a wide range of health problems, including cardiovascular disease, obesity, diabetes, depression, anxiety, digestive disorders, insomnia, and weakened immune function.",
    "What are the benefits of maintaining a healthy work-life balance": "Maintaining a healthy work-life balance reduces stress, prevents burnout, promotes overall well-being, improves relationships with family and friends, increases productivity and job satisfaction, and enhances quality of life.",
    "How does physical activity benefit mental health": "Physical activity releases endorphins, neurotransmitters that promote feelings of happiness and well-being, reduces stress hormones, improves mood, boosts self-esteem, enhances cognitive function, and reduces the risk of depression and anxiety.",
    "What are the warning signs of a heart attack": "Warning signs of a heart attack include chest pain or discomfort, shortness of breath, nausea or vomiting, lightheadedness or dizziness, pain or discomfort in the arms, back, neck, jaw, or stomach, and cold sweats.",
    "What are the benefits of regular mindfulness meditation": "Regular mindfulness meditation reduces stress, anxiety, and depression, improves focus and attention, enhances emotional regulation, promotes relaxation and better sleep, and increases overall resilience and well-being.",
    "How does sleep quality affect overall health": "Quality sleep is essential for physical and mental health, including immune function, hormone regulation, cognitive function, mood regulation, memory consolidation, and overall vitality and well-being.",
    "What are the risk factors for developing Alzheimer's disease": "Risk factors for Alzheimer's disease include age, family history of the disease, genetics, certain medical conditions, head injuries, and lifestyle factors such as smoking, physical inactivity, and poor diet.",
    "What are the benefits of regular physical activity for children and adolescents": "Regular physical activity in children and adolescents promotes healthy growth and development, improves cardiovascular health, enhances muscular strength and endurance, supports bone health, and reduces the risk of obesity and chronic diseases later in life.",
    "How does the body metabolize carbohydrates, fats, and proteins": "Carbohydrates are broken down into glucose, fats are broken down into fatty acids and glycerol, and proteins are broken down into amino acids through digestion and metabolism, providing energy and building blocks for cellular functions and tissue repair.",
    "What are the symptoms of a concussion": "Symptoms of a concussion may include headache, dizziness, confusion, nausea or vomiting, sensitivity to light or noise, blurred vision, difficulty concentrating, memory problems, and changes in mood or behavior.",
    "How does smoking affect cardiovascular health": "Smoking damages blood vessels, increases blood pressure and heart rate, reduces oxygen supply to the heart and tissues, promotes inflammation and blood clot formation, and contributes to the development of heart disease, stroke, and peripheral artery disease.",
    "What are the different stages of sleep": "Sleep consists of multiple stages, including non-rapid eye movement (NREM) sleep stages 1, 2, and 3 (deep sleep), and rapid eye movement (REM) sleep, each serving different functions in restorative sleep, memory consolidation, and brain function.",
    "What are the benefits of vaccination": "Vaccination protects against infectious diseases by stimulating the immune system to produce antibodies and develop immunity, prevents the spread of diseases within communities, reduces illness, hospitalizations, and deaths, and contributes to public health and disease eradication efforts.",
    "How does chronic inflammation contribute to disease": "Chronic inflammation is linked to the development of various health conditions, including cardiovascular disease, diabetes, autoimmune disorders, cancer, neurodegenerative diseases, and chronic pain, by damaging tissues, disrupting normal cellular functions, and promoting disease progression.",
    "What are the signs of dehydration": "Signs of dehydration include thirst, dry mouth, dark-colored urine, infrequent urination, fatigue, dizziness, lightheadedness, confusion, dry skin, and decreased tear production, indicating a lack of adequate fluid intake and potential fluid loss from the body.",
    "How does stress impact the immune system": "Stress activates the body's stress response, releasing stress hormones such as cortisol and adrenaline, which temporarily enhance immune function but can weaken the immune system over time, increasing susceptibility to infections, inflammation, and autoimmune disorders.",
    "What are the risk factors for developing osteoarthritis": "Risk factors for osteoarthritis include age, obesity, joint injury or trauma, repetitive stress on joints, genetics, gender (more common in females), bone deformities, and certain occupations or activities involving heavy lifting or repetitive movements.",
    "How does the body regulate blood pressure": "Blood pressure is regulated by the cardiovascular and nervous systems through mechanisms such as vasoconstriction (narrowing of blood vessels) and vasodilation (expansion of blood vessels), heart rate regulation, blood volume control, and hormone signaling to maintain optimal blood flow and pressure throughout the body.",
    "What is the role of antioxidants in promoting health": "Antioxidants help neutralize harmful free radicals, unstable molecules that can damage cells and contribute to oxidative stress, inflammation, and chronic diseases such as heart disease, cancer, and neurodegenerative disorders, by preventing oxidative damage and supporting cellular repair and protection.",
    "How does the body regulate blood glucose levels": "Blood glucose levels are regulated by insulin, a hormone produced by the pancreas, which helps cells absorb glucose from the bloodstream and store it for energy or use it as fuel, maintaining blood sugar levels within a narrow range to support cellular functions and metabolism.",
    "What are the symptoms of a stroke": "Symptoms of a stroke may include sudden numbness or weakness in the face, arm, or leg (especially on one side of the body), sudden confusion, trouble speaking or understanding speech, sudden trouble seeing in one or both eyes, sudden trouble walking, dizziness, loss of balance, or coordination, and sudden severe headache with no known cause.",
    "How does the menstrual cycle affect women's health": "The menstrual cycle is a normal physiological process that involves hormonal fluctuations, ovulation, and changes in the uterine lining, which regulate menstruation, fertility, and reproductive health, and may influence mood, energy levels, and physical symptoms such as cramps and bloating.",
    "What are the benefits of maintaining a healthy weight": "Maintaining a healthy weight reduces the risk of obesity-related health problems, including heart disease, diabetes, stroke, certain cancers, osteoarthritis, and sleep apnea, improves overall health and quality of life, and supports long-term well-being and longevity.",
    "How does the immune system respond to infection": "The immune system responds to infection by detecting and recognizing foreign invaders such as bacteria, viruses, parasites, and fungi, mobilizing immune cells and antibodies to destroy pathogens, and mounting an inflammatory response to contain and eliminate infections while maintaining tissue homeostasis and repair.",
    "What are the benefits of regular cholesterol screenings": "Regular cholesterol screenings help assess cardiovascular risk, identify high cholesterol levels and lipid imbalances, guide preventive measures and lifestyle modifications to lower cholesterol levels, reduce the risk of heart disease and stroke, and promote heart-healthy behaviors and treatment interventions.",
    "How does the body maintain electrolyte balance": "Electrolyte balance is maintained through processes such as renal filtration and reabsorption, electrolyte transport across cell membranes, hormonal regulation, and fluid intake and output, ensuring optimal levels of sodium, potassium, chloride, calcium, magnesium, and phosphate for cellular function and fluid balance.",
    "What are the benefits of regular breast self-exams": "Regular breast self-exams help women become familiar with their breast tissue, detect changes such as lumps, thickening, or skin abnormalities, identify potential signs of breast cancer early, and promote breast health awareness and proactive healthcare practices.",
    "How does the body respond to acute pain": "The body responds to acute pain through a complex process involving sensory perception, nerve signaling, neurotransmitter release, and activation of pain pathways in the brain and spinal cord, triggering protective reflexes, emotional responses, and behavioral adaptations to alleviate pain and promote healing.",
    "What are the symptoms of a urinary tract infection (UTI)": "Symptoms of a urinary tract infection may include frequent urination, urgency to urinate, burning or pain during urination, cloudy or foul-smelling urine, blood in the urine, pelvic pain or discomfort, and fever or chills, indicating inflammation or infection of the urinary tract.",
    "How does sleep impact cognitive function and memory": "Sleep plays a critical role in cognitive function and memory consolidation, facilitating neural processing, synaptic plasticity, and memory storage during various stages of sleep, including slow-wave sleep (deep sleep) and rapid eye movement (REM) sleep, supporting learning, problem-solving, and information retention.",
    "What are the risk factors for developing type 2 diabetes": "Risk factors for type 2 diabetes include obesity, sedentary lifestyle, unhealthy diet, family history of diabetes, ethnicity (higher risk in African American, Hispanic, Native American, and Asian American populations), age (risk increases with age), and gestational diabetes during pregnancy.",
    "What is the importance of regular dental care in overall health": "Regular dental care promotes oral health by preventing tooth decay, gum disease, and oral infections, reducing the risk of systemic health problems such as heart disease, diabetes, and respiratory infections, and supporting overall well-being, confidence, and quality of life.",
    "What are the risk factors for developing lung cancer?":
      "Risk factors for lung cancer include smoking tobacco, exposure to secondhand smoke, occupational exposure to carcinogens (such as asbestos and radon), air pollution, genetic predisposition, and a family history of lung cancer.",
    "How does the body regulate blood sugar levels in individuals with diabetes?":
      "In individuals with diabetes, blood sugar levels are regulated through medication (such as insulin or oral hypoglycemic agents), dietary management, physical activity, and monitoring blood glucose levels regularly to prevent hyperglycemia (high blood sugar) or hypoglycemia (low blood sugar) episodes.",
    "What are the benefits of regular eye exams?":
      "Regular eye exams help detect vision problems (such as refractive errors or cataracts), monitor eye health conditions (such as glaucoma or macular degeneration), identify signs of systemic diseases (such as diabetes or hypertension), and maintain optimal visual acuity and eye function.",
    "How does the body respond to allergic reactions?":
      "The body responds to allergic reactions by releasing histamine and other chemicals, triggering inflammation, swelling, itching, and other symptoms, activating the immune system to identify and neutralize allergens, and potentially causing allergic rhinitis, asthma, hives, or anaphylaxis in severe cases.",
    "What are the benefits of breastfeeding for infants and mothers?":
      "Breastfeeding provides essential nutrients, antibodies, and immune factors for infants, promotes bonding and emotional attachment between mothers and babies, reduces the risk of infections, allergies, and chronic diseases in infants, and supports postpartum recovery and maternal health for mothers.",
    "How does the body regulate temperature during fever?":
      "During fever, the body increases its core temperature in response to infection or inflammation, activating the immune system, releasing cytokines and prostaglandins, resetting the body's thermostat in the hypothalamus, and promoting heat production, shivering, and vasoconstriction to raise body temperature and combat pathogens.",
    "What are the symptoms of an allergic reaction to food?":
      "Symptoms of a food allergy may include hives, itching, swelling (of the lips, tongue, throat, or face), abdominal pain, diarrhea, nausea, vomiting, difficulty breathing, wheezing, coughing, nasal congestion, dizziness, lightheadedness, or anaphylaxis (a severe, life-threatening allergic reaction).",
    "How does physical therapy benefit patients recovering from injuries or surgeries?":
      "Physical therapy helps patients recover from injuries or surgeries by restoring mobility, strength, flexibility, and range of motion, reducing pain and inflammation, improving balance, coordination, and posture, preventing re-injury, and promoting functional independence and quality of life.",
    "What are the risk factors for developing osteoporosis?":
      "Risk factors for osteoporosis include age (especially postmenopausal women), gender (more common in females), family history of osteoporosis, low body weight, sedentary lifestyle, smoking, excessive alcohol consumption, poor nutrition (low calcium or vitamin D intake), and certain medications (such as corticosteroids or anticonvulsants).",
    "How does stress affect gastrointestinal health?":
      "Stress can affect gastrointestinal health by altering gut motility, increasing stomach acid production, exacerbating symptoms of acid reflux or irritable bowel syndrome (IBS), disrupting the gut microbiota, impairing digestion and nutrient absorption, and contributing to gastrointestinal disorders or functional gastrointestinal disorders.",
    "What are the benefits of early detection and treatment of cancer?":
      "Early detection and treatment of cancer increase the chances of successful outcomes, improve treatment options and prognosis, reduce the risk of cancer progression or metastasis, minimize the need for aggressive interventions, and enhance quality of life and survival rates for cancer patients.",
    "How does the body metabolize medications?":
      "Medications are metabolized in the liver through enzymatic processes such as oxidation, reduction, hydrolysis, and conjugation, converting drugs into metabolites that are more easily excreted by the kidneys or eliminated from the body, affecting drug efficacy, bioavailability, and toxicity.",
    "What are the benefits of regular stretching exercises?":
      "Regular stretching exercises improve flexibility, joint range of motion, and muscle elasticity, reduce muscle tension and stiffness, alleviate muscle soreness and discomfort, improve posture and alignment, enhance athletic performance, and prevent injuries during physical activities.",
    "How does nutrition impact skin health?":
      "Nutrition plays a key role in skin health by providing essential nutrients (such as vitamins, minerals, antioxidants, and fatty acids) that support collagen production, skin regeneration, and barrier function, promoting hydration, elasticity, and resilience, and preventing premature aging, dryness, or skin disorders.",
    "What are the benefits of mindfulness-based stress reduction techniques?":
      "Mindfulness-based stress reduction techniques help individuals manage stress, anxiety, and depression, cultivate awareness, attention, and emotional regulation, promote relaxation and mindfulness practices (such as meditation, deep breathing, and body scanning), enhance resilience, and improve overall well-being and mental health.",
    "How does chronic pain affect quality of life?":
      "Chronic pain can significantly impact quality of life by causing physical discomfort, fatigue, sleep disturbances, reduced mobility and functional limitations, emotional distress (such as anxiety, depression, or irritability), social isolation, impaired work productivity, and decreased overall satisfaction and enjoyment of life.",
    "What are the benefits of regular cardiovascular exercise?":
      "Regular cardiovascular exercise strengthens the heart muscle, improves circulation and blood flow, lowers blood pressure and cholesterol levels, enhances aerobic capacity and endurance, promotes weight management, reduces the risk of cardiovascular disease, stroke, and diabetes, and supports overall cardiovascular health and longevity.",
    "How does the body respond to chronic stress?":
      "Chronic stress triggers the body's stress response, leading to sustained release of stress hormones (such as cortisol and adrenaline), dysregulation of the hypothalamic-pituitary-adrenal (HPA) axis, immune suppression, inflammation, oxidative stress, and disruptions in sleep, appetite, mood, and cognitive function, contributing to physical and mental health problems.",
    "What are the risk factors for developing rheumatoid arthritis?":
      "Risk factors for rheumatoid arthritis include genetic predisposition, family history of the disease, environmental factors (such as smoking or exposure to certain viruses or bacteria), hormonal changes, obesity, and systemic inflammation, triggering autoimmune reactions and joint inflammation.",
    "How does the body regulate blood clotting?":
      "Blood clotting (or coagulation) is regulated by a complex cascade of biochemical reactions involving platelets, clotting factors, and blood vessel walls, forming fibrin clots to stop bleeding, maintain hemostasis, and repair damaged blood vessels while preventing excessive clot formation (thrombosis) or bleeding disorders.",
    "What are the symptoms and risk factors associated with cardiovascular disease?":
      "Symptoms of cardiovascular disease may include chest pain, shortness of breath, palpitations, fatigue, and dizziness. Risk factors include high blood pressure, high cholesterol, smoking, diabetes, obesity, sedentary lifestyle, and family history of heart disease.",
    "How does the immune system respond to infections?":
      "The immune system responds to infections by recognizing pathogens, producing antibodies, activating immune cells (such as T cells and B cells), and mounting an inflammatory response to neutralize and eliminate the invading microorganisms.",
    "What are the benefits of vaccination?":
      "Vaccination helps prevent infectious diseases by stimulating the immune system to produce antibodies against specific pathogens, reducing the risk of illness, complications, and transmission of infectious agents within communities.",
    "How does exercise benefit mental health?":
      "Exercise promotes mental health by releasing endorphins and neurotransmitters (such as dopamine and serotonin), reducing stress hormones, improving mood, cognitive function, and sleep quality, and enhancing self-esteem and overall well-being.",
    "What role do vitamins and minerals play in maintaining health?":
      "Vitamins and minerals are essential nutrients that support various physiological functions, including metabolism, immune function, bone health, tissue repair, antioxidant defense, and neurotransmitter synthesis.",
    "What are the common signs and symptoms of depression?":
      "Common signs and symptoms of depression include persistent sadness, loss of interest or pleasure in activities, changes in appetite or weight, sleep disturbances, fatigue, feelings of worthlessness or guilt, difficulty concentrating, and thoughts of death or suicide.",
    "How does stress impact the gastrointestinal system?":
      "Stress can disrupt gastrointestinal function by altering gut motility, increasing gut permeability, exacerbating symptoms of irritable bowel syndrome (IBS) or inflammatory bowel disease (IBD), and contributing to gastrointestinal disorders such as ulcers or acid reflux.",
    "What are the benefits of maintaining a healthy diet?":
      "Maintaining a healthy diet provides essential nutrients, supports energy metabolism, regulates blood sugar levels, promotes cardiovascular health, reduces the risk of chronic diseases (such as diabetes, obesity, and hypertension), and supports overall well-being and longevity.",
    "How does the body regulate blood pressure?":
      "Blood pressure is regulated by the cardiovascular and nervous systems, adjusting the contraction and relaxation of blood vessels, cardiac output, and fluid balance to maintain optimal blood flow and perfusion to organs and tissues.",
    "What are the risk factors for developing osteoarthritis?":
      "Risk factors for osteoarthritis include aging, obesity, joint injury or trauma, repetitive stress on joints, genetics, and underlying conditions such as rheumatoid arthritis or joint deformities.",
    "How does the body respond to acute pain?":
      "The body responds to acute pain by releasing neurotransmitters and activating pain receptors (nociceptors), triggering an immediate protective response, such as withdrawal reflexes, increased heart rate, and stress hormone release, to signal tissue damage or injury.",
    "What are the benefits of adequate hydration?":
      "Adequate hydration supports cellular function, regulates body temperature, facilitates nutrient absorption and waste removal, lubricates joints, supports cardiovascular function, enhances cognitive performance, and promotes overall health and well-being.",
    "How does smoking tobacco affect respiratory health?":
      "Smoking tobacco damages the respiratory system by causing inflammation, narrowing airways, reducing lung function, impairing ciliary function (which clears mucus and debris), increasing mucus production, and contributing to respiratory infections, chronic bronchitis, emphysema, and lung cancer.",
    "What is the importance of regular health screenings?":
      "Regular health screenings help detect early signs of diseases or conditions, facilitate early intervention and treatment, monitor health status and risk factors, prevent complications, and promote overall health maintenance and disease prevention.",
    "How does the body regulate fluid and electrolyte balance?":
      "Fluid and electrolyte balance is regulated by the kidneys, hormones (such as aldosterone and antidiuretic hormone), and electrolyte transport mechanisms, maintaining proper hydration, osmolarity, and pH balance within the body's cells and extracellular fluid compartments.",
    "What are the benefits of practicing good sleep hygiene?":
      "Practicing good sleep hygiene promotes restful sleep by establishing a regular sleep schedule, creating a conducive sleep environment, avoiding stimulants before bedtime, engaging in relaxation techniques, and prioritizing sleep as an essential component of overall health and well-being.",
    "How does the body respond to dehydration?":
      "Dehydration triggers physiological responses such as increased thirst, reduced urine output, dry mouth, fatigue, dizziness, headaches, dark urine, and electrolyte imbalances, compromising cellular function, kidney function, and overall health.",
    "What are the benefits of regular physical activity for children and adolescents?":
      "Regular physical activity promotes healthy growth and development, strengthens muscles and bones, improves cardiovascular fitness, enhances motor skills and coordination, reduces the risk of obesity, diabetes, and hypertension, and supports overall physical and mental well-being.",
    "How does chronic inflammation contribute to the development of chronic diseases?":
      "Chronic inflammation contributes to the development of chronic diseases by damaging tissues, promoting oxidative stress, impairing immune function, disrupting cellular signaling pathways, and contributing to the pathogenesis of conditions such as cardiovascular disease, diabetes, cancer, and autoimmune disorders.",
    "What are the benefits of stress management techniques?":
      "Stress management techniques help reduce the physiological and psychological effects of stress by promoting relaxation, reducing muscle tension, improving coping skills, enhancing resilience, and preventing stress-related health problems such as anxiety, depression, and cardiovascular disease.",
    "What are the risk factors for developing type 2 diabetes?":
      "Risk factors for type 2 diabetes include obesity, sedentary lifestyle, family history of diabetes, age, high blood pressure, high cholesterol levels, and certain ethnic backgrounds.",
    "How does the body regulate blood glucose levels?":
      "Blood glucose levels are regulated by insulin and glucagon, hormones produced by the pancreas. Insulin lowers blood sugar levels by facilitating glucose uptake by cells, while glucagon raises blood sugar levels by promoting glucose release from the liver.",
    "What are the potential complications of untreated hypertension?":
      "Untreated hypertension can lead to complications such as heart disease, stroke, kidney damage, vision loss, peripheral artery disease, and cognitive decline.",
    "How does the body respond to acute inflammation?":
      "The body responds to acute inflammation by increasing blood flow to the affected area, releasing white blood cells to fight off pathogens, and triggering the production of inflammatory mediators to remove damaged cells and initiate tissue repair.",
    "What role do antioxidants play in maintaining health?":
      "Antioxidants help neutralize free radicals, which are unstable molecules that can damage cells and contribute to aging and disease. Antioxidants protect cells from oxidative stress and reduce the risk of chronic diseases.",
    "How does the body metabolize carbohydrates, fats, and proteins?":
      "Carbohydrates are broken down into glucose, fats into fatty acids, and proteins into amino acids during digestion. These nutrients are then metabolized by cells for energy production, storage, and tissue repair.",
    "What are the signs and symptoms of a stroke?":
      "Signs and symptoms of a stroke include sudden weakness or numbness of the face, arm, or leg, confusion, trouble speaking or understanding speech, trouble seeing in one or both eyes, dizziness, and severe headache.",
    "How does chronic stress affect the immune system?":
      "Chronic stress can weaken the immune system by increasing levels of stress hormones such as cortisol, which suppress immune function and make individuals more susceptible to infections and illness.",
    "What are the benefits of maintaining a healthy body weight?":
      "Maintaining a healthy body weight reduces the risk of obesity-related conditions such as type 2 diabetes, heart disease, stroke, hypertension, certain cancers, and musculoskeletal disorders.",
    "How does the body regulate hunger and satiety?":
      "Hunger and satiety are regulated by hormones such as ghrelin, which stimulates appetite, and leptin, which signals fullness and suppresses appetite. These hormones interact with the brain to regulate food intake and energy balance.",
    "What are the effects of chronic sleep deprivation?":
      "Chronic sleep deprivation can lead to cognitive impairment, mood disturbances, increased risk of accidents and injuries, weakened immune function, weight gain, diabetes, hypertension, and heart disease.",
    "How does the body adapt to regular exercise?":
      "The body adapts to regular exercise by increasing cardiovascular fitness, building muscle strength and endurance, improving flexibility and coordination, and enhancing overall physical performance and health.",
    "What are the benefits of maintaining good oral hygiene?":
      "Maintaining good oral hygiene reduces the risk of dental caries, gum disease, and tooth loss, improves oral health and breath freshness, and may lower the risk of systemic conditions such as heart disease and diabetes.",
    "How does the body respond to chronic pain?":
      "The body responds to chronic pain by sensitizing pain receptors, altering pain perception, causing changes in mood and behavior, disrupting sleep patterns, and impairing overall quality of life.",
    "What are the long-term effects of untreated mental health disorders?":
      "Untreated mental health disorders can lead to chronic psychological distress, impaired social functioning, decreased productivity, increased risk of substance abuse, and higher mortality rates.",
    "What are the benefits of regular meditation or mindfulness practice?":
      "Regular meditation or mindfulness practice can reduce stress, promote relaxation, improve emotional well-being, enhance concentration and cognitive function, and cultivate a greater sense of self-awareness and compassion.",
    "How does the body regulate blood coagulation and prevent excessive bleeding?":
      "Blood coagulation is regulated by a complex system of clotting factors and platelets that form clots to stop bleeding. The body also produces anticoagulants to prevent excessive clot formation and maintain blood flow.",
    "What are the risk factors for developing skin cancer?":
      "Risk factors for skin cancer include excessive sun exposure, history of sunburns, fair skin, family history of skin cancer, presence of moles or unusual skin lesions, and exposure to ultraviolet radiation from tanning beds or lamps."
};
export default questionAnswerMap;